### PR TITLE
don't create files directory

### PR DESCRIPTION
**Pull request by adamcstephens**
Nessus manages this directory and will delete it on log out. Puppet will constantly recreate it.

### CODE REVIEW

**Comment by adamcrews** [comment]
I believe that the files directory is required by nessus5, however I don't have a nessus setup at my fingertips to play with to be sure.  I am hesitant to merge this until we can verify that nessus 5 will still be ok.  If someone else can verify this for nessus 5 before I can, then I'm ok to merge it.

Also before merging, could you update the spec tests so that the files directory is no longer checked as part of the tests?

**Comment by adamcstephens** [comment]
I tested Nessus 5.2.7, which does the same as 6.1.2. When a user logs in, the files directory is created. When the user logs out, the files directory is deleted.

**Comment by adamcstephens** [comment]
Hi @adamcrews, any update on this? Thanks.

**Comment by adamcrews** [comment]
Thanks for the PR!

**Comment by adamcstephens** [comment]
Thanks for being so responsive!

**Pull request merged**
